### ISSUE TITLE
Navigation board and figurines, how -to

### ISSUE THREAD

**Issue by chessjohn2018** [yo35/rpb-chessboard#115]
Can anyone tell me how to add a navigation board to a chess game?
Can anyone telle me how to show the figurines instead of the Letters for the chess pieces?

**Comment by yo35** [comment]
Hi,
In the admin part of your website, in the left sidebar, there is a menu Chess > Settings. Plugin configuration is managed from there.

**Comment by SpawnL** [comment]
@yo35 Can you please answer the first question? How to add a navigated chessboard of a game to the page, instead of having a pop up chessboard? Thank you

**Comment by yo35** [comment]
Hi,

As I said, you must have a look to the page where the plugin configuration is managed. That is in the admin part of your website, in the left sidebar, menu "Chess" > "Settings".

Then there is a section "Position of the navigation board", that allows you to have the navigation chessboard within the page instead of within a popup. There is also a section "Piece symbols" to have the figurines instead of the letters for the chess pieces.

**Comment by SpawnL** [comment]
@yo35 Thank you very much for the response. Wow, it's now almost perfect!

I have 1 more question, is it possible somehow to set different sizes for the interactive board (larger), and the position diagrams {[#]} (smaller)?

**Comment by yo35** [comment]
Currently, this is not possible. However, a similar request has been expressed by another user in #131 (see the end of the discussion), so I think of implementing it in some way.

**Comment by SpawnL** [comment]
@yo35 Thank you very much for you brilliant work!

**Comment by yo35** [comment]
@SpawnL As of RPB Chessboard 7.2 (just released), it is possible to set different sizes for the navigation board and for the diagrams.
