### ISSUE TITLE
Page jumps on iPad / iPhone

### ISSUE THREAD

**Issue by richiwalt** [yo35/rpb-chessboard#129]
The behavior is slightly different ... but the main problem remains on my site.   I’ve commented on the original ticket with details.   This post may be deleted if those comments are seen.  

Thanks

Richard.

**Comment by yo35** [comment]
Hi Richard,
In the comments of #128, you've mentioned "Looks like it is trying to make the mouse clicked move be at the very top of the page". The actual behavior -- in the popup frame mode -- is that the plugins tries to scroll the page so that the selected move is visible. This is the behavior requested in #28.

I've just re-tested this feature, and it looks mostly OK for me: if the selected moved is already visible, no scrolling happens. Scrolling towards the bottom of the page is also OK. Only scrolling towards the top of the page may not take into account the admin bar thickness, but I think this is a rather minor issue.

Then, without accessing to your website, I cannot guess what is wrong. May be there is something specific due to your theme, maybe something else.

**Comment by richiwalt** [comment]
Yoann,

Belay all my comments ... I posted in haste.  

Sincere apologies.  I see it's actually working quite nicely on a desktop computer.  All my comments were made with an incorrect assumption that the gigantic 12.9" iPad Pro (very large ... and normally ignores any "small screen" display differences) behavior would be the same as a regular desktop behavior.

So ... all that to say ... I initially tested the fix on my iPad.  The Desktop works perfectly.

So, this begs the question:  The iPad used to have the exactly same behavior as a normal computer display ... it would correctly scroll the page only if the move posted print was not visible ... and if it was, it would not move the page.

So, curious ... do you have any ideas about why the iPad is different now ?  It used to work just fine.  Not sure when it changed.  As I said in the initial ticket, it has been a while since I used the site.  

I certainly do not expect you to complicate things with supporting multiple devices ... but, picking your brain ... would you think this was in Javascript somewhere ?  Or in iOS ?  Have you heard if android has the same problems that Apple devices have here? (Might be a good 1/2 split test to see if this is related to iOS).  If it were in Javascript for "small scree devices" ... I might like to play with discovering a fix ...  I really used to use the iPad a lot with my site ... that will have to change if I can not find a fix.

BTW ... if you email me privately, I can give you guest access to my site with a restricted guest account.  

Thanks for any response (and I do not know what time it is in your world - hope I'm not disturbing you - it's 7:45 am here.  :-)   )

**Comment by yo35** [comment]
Hi Richard,

I've tried on Chrome on Android, everything seems to be fine.

This problem you encounter on iPad, have you observed it with any browser? Or just with the default browser, which I guess is Safari?

**Comment by richiwalt** [comment]
I am observing it in every browser on the iPad.    Any ideas ?
  

  
I would be happy to give you a username and password to check the sit out to see if there is some combination of plugins or theme ... just need you to email me privately so as it’s not posted to the thread.    
  

  
Thanks for any suggestions.    
  

  
Richard.    
  

  
  

  
  
>

**Comment by sabapathee** [comment]
Hi,
I have the same issue on iOS11.3 (with Safari and Chrome) when I use the navigation bar to view the next moves, the screen jumps to the top.
On desktop, it is OK I don’t have the issue when I use the responsive mode in Google Chrome or Safari.
Here is the site: https://wordpress.project-toolbox.fr/test-rpb-chessboard/ 
(I use RPB Chessboard plugin version 5.2.1)

**Comment by yo35** [comment]
Hi all,
Since I don't have any iOS device, I'll need your help to validate a bugfix.

Could you have a look to the following page, and tell me whether it behaves as expected or not on an iPhone or an iPad:
https://rpb-chessboard.yo35.org/temporary-simple-chess-game-within-a-long-page/

If OK, I will release a new version of the plugin including the bugfix.

**Comment by sabapathee** [comment]
Hi,
It works as expected !
I will update the new version as soon as it will available.
Thanks

**Comment by yo35** [comment]
Fix in version 5.2.2 (just released).
Thanks for your help.
