### ISSUE TITLE
Struggling with RPB Chessboard

### ISSUE THREAD

**Issue by bcomeaux81** [yo35/rpb-chessboard#161]
Hello, I'm trying to post these [three matches](https://www.chess.com/article/view/the-amazing-argentinian-chess-tragedy) from the Argentinian Tragedy.  It not working though.  Does anyone have any idea what I'm doing wrong.  I'm copying the entire pgn and putting it between [pgn] [/pgn].  Any help would be appreciated.

**Comment by yo35** [comment]
Hi,
Can you provide more details about what is not working? And maybe attach the PGN file to this post so that I could see if there is something wrong with it.

**Comment by bcomeaux81** [comment]
Let’s just say this one.  I tried many.

[Pgn]Event “Gothenburg Interzonal 1955”]
[Site “?”]
[Date “????.??.??”]
[Round “?”]
[White “Paul Keres”]
[Black “Oscar Panno”]
[Result “1-0”]
[WhiteElo “”]
[BlackElo “”]
[ECO “”]

1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6 { Keres wrote: “The variation in the Sicilian Defense chosen by Black here was very popular at Gothenburg and new methods of development were discovered, both for White and for Black. In the present game White employs a continuation that is nowadays very well known but was practically new territory at Gothenburg.” } 6.Bg5 e6 7.f4 { In 1955 the popular move was 7.Qf3. } 7…Qb6 8.Qd2 Nc6 { Of course 8…Qxb2 is the critical move, but since the position after 8.Qd2 was first played in 1954 in the game Nezhmetdinov vs. Shcherbakov (it was drawn), the whole thing was pretty much unknown. Daring to chop by 8…Qxb2 against an attacker like Keres would probably feel like suicide to a positional player like Panno. Thus, Panno avoided it. I will add that a few rounds later Fuderer tried this same line against Keres and, instead of Panno’s 8…Nc6, he braved 8…Qxb2. Unfortunately Black lost in 18 moves. } 9.O-O-O Qxd4 10.Qxd4 Nxd4 11.Rxd4 Nd7 12.Be2 h6 13.Bh4 g5 14.fxg5 Ne5 15.Na4 Be7 16.Nb6 Rb8 17.Bg3 hxg5 18.Rhd1 f6 19.c4 O-O 20.R4d2 f5 21.c5 f4 22.cxd6 Bxd6 23.Rxd6 fxg3 24.hxg3 Rf7 25.Kb1 Rc7 26.Rd8+ Kg7 27.Rc1 Nc6 28.e5 Kg6 29.Bd3+ Kf7 30.Rh8 Ke7 31.Bg6 { , 1-0 since 32.Re8 mate was threatened. } 1-0[/pgn]

**Comment by yo35** [comment]
Hi,
- The shortcode must be `[pgn]` (lower case), not `[Pgn]` as in your example,
- You missed a square bracket before `Event`,
- And the main problem is that, for some reasons, the straight double quote characters ( " )of the original PGN text have been transformed into curved double quote characters ( “ and ” ). This is probably because the PGN has been copy-pasted into MS Word or something similar at some point.

When I go to https://www.chess.com/article/view/the-amazing-argentinian-chess-tragedy, I click on the "Share" button on the first game, then "PGN" tab, CTRL+C to copy the PGN, and I paste it between `[pgn][/pgn]` in a shortcode block the WordPress editor, the result is OK:

![pgn](https://user-images.githubusercontent.com/5740068/75622928-cd47fd00-5ba5-11ea-8473-fb008a559d15.png)

**Comment by yo35** [comment]
Is it OK now?

**Comment by bcomeaux81** [comment]
I got rid of my site
