### ISSUE TITLE
rpb-chessboard does not work with theme The Thinker Lite

### ISSUE THREAD

**Issue by Taimanov** [yo35/rpb-chessboard#162]
Hi, I changed the theme of my blog but now the rpb-chessboard no longer displays the games on the PC. However, it shows the games on mobile. What might be the reason and how can I fix that?

Thanks for help!

**Comment by yo35** [comment]
Hi, and sorry for the late reply,
I've tried the Thinker Lite theme, and I haven't noticed any issue with it, either on PC or mobile.

Here is what I've obtained on PC:
![thinker-lite](https://user-images.githubusercontent.com/5740068/78820112-8f759a00-79d7-11ea-8866-37e970a9ae06.png)

Maybe something else prevent rpb-chessboard from working properly (another plugin?). Is it possible to have the address of your website in order to have a look?

**Comment by yo35** [comment]
No news for more than 5 months, I close this issue.
