### ISSUE TITLE
Is there a way to highlight last move for the {[#]} Chess display during pgn?

### ISSUE THREAD

**Issue by leonfresh** [yo35/rpb-chessboard#182]
Hi I'm having to manually highlight the last move. Is there some kind of option to automatically do so for when I want to insert the {[#]} diagram during PGN , and if not can you make one? Thanks.

**Comment by yo35** [comment]
Hi,
Sorry for the late reply. I'm not sure to understand what you want to do here. Can you give more explanations, maybe with a screenshot?

**Comment by leonfresh** [comment]
Yeah sure, for example on this article:
https://chesstuts.com/aggressive-closed-sicilian-grand-prix-against-a-higher-rated-player-2241-elo/

I have to manually draw arrows for my last move on the diagrams. Is there a
way  for this to be automatic via an option?

**Comment by yo35** [comment]
OK, I think I understand: you would expect to have the blue arrow showing the last move in the inline diagrams, and to have it drawn automatically, similarly to what exists in the navigation board:
![blue-arrow](https://user-images.githubusercontent.com/5740068/99273857-d824e980-2829-11eb-9da5-e315fdc78013.png)

Currently, this is not possible to have it drawn automatically: you must manually add the `[%cal G/Y/Rb1c3]` annotations to highlight piece displacements in the inline diagrams.

I must say I've done it this way on purpose: as an chess game annotator, when you insert an inline diagram, it means you want to highlight something related to the corresponding position. It can be the latest move, but it can be something else: a threat, a pawn structure, a weak square... Having an arrow showing the latest move would pollute the message if this is not what the annotator wants to highlight.

The situation is different in the navigation board, that is a dynamic object by design, and whose role is to allow the reader to follow the game -- and not to highlight such or such situation.

**Comment by leonfresh** [comment]
Yeah I know what you mean how you done this on purpose to make it clear to
the annotator. But like I said, could there be a possible Option in the
shortcode to enable this functionality? It would save a lot of hassle to
illustrate the last move, rather than making the arrow on every [#]
picture.

It could also be in the form of highlighted squares (previous and current)
rather than an arrow, as in many chess sites.

**Comment by yo35** [comment]
If there were a shortcode attribute (for instance: `[pgn show_last_move_arrow_in_diagrams=true]`) to control this behavior, that would be it would apply to all the diagrams within a given game. This is what you want to do, but this may not be the suitable behavior in all cases: as an annotator working on a given game, I may want to insert a diagram to illustrate the latest move at some point in the game, and later I may want to insert a diagram to highlight something else - within the same game.

For this reason, I prefer to keep it that way, i.e. simple, with no magic behavior behind.

**Comment by leonfresh** [comment]
I don't really get this logic you said because the annotator by configuring
that shortcode function, willingly knows that *all* diagrams in this pgn
will come with a last move highlight. If anything it will always be a
positive feature since if they don't want it, they don't have to add that
in the shortcode.

**Comment by yo35** [comment]
My point is: I think the situations in which this feature would be usable are likely to be extremely reduced. And since the manpower and time dedicated to develop and maintain the RPB Chessboard plugin is not infinite, I don't think it's worth it... Especially since what you want to do is already feasible, in a way that offers more flexibility.

**Comment by leonfresh** [comment]
Ok you said there's limited resources, I can pay for such a feature if
needed, tell me the price, thanks.

**Comment by leonfresh** [comment]
As you see by a new article on my site by another author, it lacks the
last-move arrows or square highlights and a lot of them seem empty and the
people don't know what was the last move.
https://chesstuts.com/my-first-win-against-a-fide-master-in-classical-bd3-french/

**Comment by leonfresh** [comment]
Most authors wont be bothered to draw the last move arrow in.
