### ISSUE TITLE
Antichess Variant

### ISSUE THREAD

**Issue by ALharchi** [yo35/rpb-chessboard#187]
Hello,
Would it be possible to add support to Antichess Variant? See here: https://lichess.org/variant/antichess

It might be complicated, but maybe a start would be just disabling all checks for a valid move/position? What would be your suggestion for that?

Thanks in advance.

**Comment by yo35** [comment]
Hi,
It should be feasible (obviously the antichess is not the most complicated variant to implement). Still, I have to figure out how to switch properly from one variant to another in the code, without duplicating to many things. I'll look at that.

**Comment by ALharchi** [comment]
Any chance this will see the light soon? Thanks :)

**Comment by yo35** [comment]
Not at the top priority currently...

**Comment by yo35** [comment]
This is available in RPB Chessboard version 6.2.0 (just released).

Currently, the antichess games must contain the PGN header `[Variant "Antichess"]` so that they can be recognized as such. This corresponds to the Lichess convention, but my guess is that PGN files generated by other websites may follow a different convention (e.g. `[Variant "Giveaway"]`, `[Variant "Suicidechess"]` or whatever...). If this is the case, and if you encounter some problem with these kind of headers, please let me know.
