### ISSUE TITLE
Troubles with uploading pages in Firefox

### ISSUE THREAD

**Issue by UnoScacchista** [yo35/rpb-chessboard#188]
HI there. Since some days I noticed that very often the pages of my WordPress.com blog (https://unoscacchista.com/) do not upload using Firefox (v.84.0 on MacOS Mojave, v.10.14.6), remaining on hold indefinitely. Apparently there are no problems with other browsers.
Everything goes back to normal if I deactivate the rpb-chessboard plug-in.
Is this a known behavior? Any word of advice?
Thank you.

**Comment by yo35** [comment]
Hi,
I've never heard of a problem like this, but I'm not sure it is caused by RPB Chessboard. My guess is that there is an issue with your theme (Newsphere), and more specifically the preload feature that comes with it.

Indeed, I've downloaded Newsphere on my test website, disabled all the plugins, and I've able to reproduce the problem in these conditions. On the other hand, if I disable the preloader (in the admin > "Appearance" > "Customize" > "Theme options" > "Preloader options"), everything is fine.

**Comment by UnoScacchista** [comment]
Excellent! It worked like a charm. Thank you so much for having checked that out.
