### ISSUE TITLE
Squares instead of ciricles to highlight squares

### ISSUE THREAD

**Issue by ChessGuy** [yo35/rpb-chessboard#193]
Hello,

After the update, the [%csl] command produces a circle instead of a square to highlight parts of the board.  I liked the squares better.  Is there a way to change this setting?

**Comment by yo35** [comment]
Hi,
In the version just released (5.9.1), I've changed the aspect of the [%csl] markers again : they are now rendered as a plain circle, which is more close to what they used to look like. I don't want to come back to the initial rectangle aspect, since it has some drawbacks, in particular it hides the square edges when several neighbor square are highlighted.

It is not possible to customize the shape used to render the [%csl] markers, and I don't want to change that: allowing this kind of customization would increase the complexity of the code for a small added-value.

I mention it is possible since version 5.9.0 to customize the color of the markers if you are not pleased with the color contrast between squares and markers. See in the admin, menu 'Chess' > 'Theming' > create a new colorset.

**Comment by ChessGuy** [comment]
Thanks for the update.  I like the filled in circle much more than the hollow one.

**Comment by yo35** [comment]
I've received several complains regarding the new aspect of square markers, so I've changed my mind and rollback to what it used to be until 5.9.0, i.e. plain rectangles.

This rollback is available in version 5.9.2 (just released).

**Comment by dredaz** [comment]
Thank you. Still have problem with small square size. My square size is 33, and it look like this:
![Capture](https://user-images.githubusercontent.com/33801681/107360287-4961f900-6b08-11eb-9eb6-37556f2aa653.PNG)

**Comment by yo35** [comment]
Hi,
What is your website?
