### ISSUE TITLE
Conflict between RPB Chessboard and WordPressChess

### ISSUE THREAD

**Issue by Alex10293847** [yo35/rpb-chessboard#195]
Hi, I have 2 plugins on my website.

RPB Chessboard and WordPressChess. When I activate the paid WordPressChess plugin, all my configurations from RPB get messed up. The chessboards suddenly appear huge on the pages and the usability is not good anymore.

If i activate de Compatibility mode, the chessboards don't show at all, only the code is to be seen then.

Any idea on how to solve this??
Website is masterchess.es and an example where I have the chessboards could be this one: https://www.masterchess.es/acceso-nivel-1/tactica-la-clavada/

Any help is really appreciated!

**Comment by yo35** [comment]
Hi,
I don't see any issue on the given page:

![no-issue](https://user-images.githubusercontent.com/5740068/108252141-96714b00-7158-11eb-9f1d-4fb0521027db.png)

It looks OK to me.

**Comment by Alex10293847** [comment]
Of course not, because I deactivated the WordPressChess Plugin. If I activate it, the chessboards become huge.

**Comment by yo35** [comment]
WordPressChess uses the same wordpress shortcodes as RPB Chessboard, i.e. `[fen][/fen]` and `[pgn][/pgn]`. If you want to use both plugin at the same time, you must activate the compatibility mode:

![compat_mode](https://user-images.githubusercontent.com/5740068/108590890-2506e780-7366-11eb-961c-9a97361136e0.png)

In compatibility mode, RPB Chessboard uses the shortcodes `[fen_compat][/fen_compat]` and `[pgn_compat][/pgn_compat]`, thus letting `[fen][/fen]` and `[pgn][/pgn]` available for other chess plugins. You must also edit the existing pages/posts that used `[fen][/fen]` and `[pgn][/pgn]`, and replace them with `[fen_compat][/fen_compat]` and `[pgn_compat][/pgn_compat]`.

An alternative workaround would be to configure WordPressChess so that this plugin does not use `[fen][/fen]` and `[pgn][/pgn]`. But I don't know whether it is possible or not.
