### ISSUE TITLE
How do I post the game code on a page?

### ISSUE THREAD

**Issue by twistedladders** [yo35/rpb-chessboard#203]
I am absolutely new to programming and new to blogging.  Specifically WHERE do I add the PGN game code in Wordpress?  For example, which "block" would I choose from ? I don't see any block related top chess or chess diagrams appearing in the choice of blocks after I downloaded and activated RPB.  I tried pasting the PGN code in the <code> block and it just gives the actual text of the pgn code. I've tried pasting it any plain text and same thing...  Please help I am very new to this and would love to include chess diagrams in my posts.

-Stephen

**Comment by yo35** [comment]
Hi,
You must use a "Shortcode" block.

**Comment by twistedladders** [comment]
Thank you very much. 2 more quick questions   
1)  Is there a Wordpress theme that works best to support RPB? 
2) do I need to manually add anything else (within the block like some same tag before of after)into the short code or just paste in exactly what is copied into the clipboard from a pgn file?
Sorry for the questions I have no experience coding and this is new to me. 

Stephen.

**Comment by yo35** [comment]
1. RPB Chessboard works with most of the themes.
2. Everything is detailed in the plugin help. See in the admin of your website, menu 'Chess' > 'Help'.

**Comment by ChessLovers** [comment]
Hi. 

[pgn url="https://examples.com/wp-content/plugins/rpb-chessboard/**examples.pgn**" game=0]

Where to upload the pgn? I have downloaded the pgn from chessgames.com but when I supposed to upload the pgn to?

Thank you.

**Comment by yo35** [comment]
@ChessLovers Answered in #214

**Comment by ChessLovers** [comment]
It is so strange.

[pgn url="https://examples.com/wp-content/plugins/rpb-chessboard/examples.pgn" game=0] was working yesterday and I could move the pieces on the interactive board. However, all of a sudden, the interactive board is not showing on my website anymore.

I am not sure if it is due to my enbedding of chessbase links such as tactics and livechess. 

Any idea why and how to resolve the issue?

**Comment by yo35** [comment]
@ChessLovers I suggest you open a new GitHub issue dedicated to the problem you encounter, in order to avoid cross-discussions on non-related subjects within the same issue.

Also, if you want your problem to be analyzed and eventually fixed, please provide the address of the page on which you encounter it.

**Comment by yo35** [comment]
No news on this issue for more than 1 year => closing...
