### ISSUE TITLE
No RPB Icon in editor after last update to 6.0.1

### ISSUE THREAD

**Issue by bundyal69** [yo35/rpb-chessboard#206]
Hi,
just updated from 5.9.3 to the newest version and lost the plugin icon in the tools of my editor.
Any ideas here?
Attached screenshots from prod and test stage with 5.9.3. and 6.0.1.

![before and after](https://user-images.githubusercontent.com/85118487/120206372-6cd1c080-c22b-11eb-8de4-d85b628c9757.JPG)
Thanks and best regards,
Al

**Comment by yo35** [comment]
Hi,
As of version 6.0.0, the support for the old WordPress page/post editor (TinyMCE) has been dropped: now, the plugin provides instead a chess position edition tool for the Gutenberg page/post editor, which has been the default editor in WordPress since late 2018.
Due to limited resources, the chess position edition tool in TinyMCE will not be restored, sorry if you are still using it. Though, it is still possible to edit chess diagram "manually" (by using the `[fen]...[/fen]` shortcode).
