### ISSUE TITLE
Where and how to add pgn url?

### ISSUE THREAD

**Issue by ChessLovers** [yo35/rpb-chessboard#215]
Hi. 

![short code](https://user-images.githubusercontent.com/91118138/134374834-15887bb7-d5be-4a73-a9bc-d45352644a00.png)
[pgn url="https://examples.com/wp-content/plugins/rpb-chessboard/examples.pgn" game=0] was working yesterday and I could move the pieces on the interactive board. However, all of a sudden, the interactive board is not showing on my website anymore.

I am not sure if it is due to my enbedding of chessbase links such as tactics and livechess.

Any idea why and how to resolve the issue?

If I were to use the WP block editor, where do I place this link
[pgn url="https://examples.com/wp-content/plugins/rpb-chessboard/examples.pgn" game=0] ?

I inserted it in the short code box but it is not working. I have already added the pgn file to my media. 

My website URL: https://chesslovers.reviewston.com/interactive-chess/

Thank you.

**Comment by yo35** [comment]
Hi,
The `[pgn ... ]` shortcode must be put in a so-called "shortcode block", as follows:

![shortcode_block_1](https://user-images.githubusercontent.com/5740068/134397922-9696926e-b549-414c-81b6-74b5edf4b27f.png)

... and then:

![shortcode_block_2](https://user-images.githubusercontent.com/5740068/134397965-e98dba9e-1192-424e-9152-2d9d66d5880c.png)

Hoping it solves your problem. If not, I will need the URL of an article in which you encounter those "this block contains unexpected or invalid content" blocks.

**Comment by ChessLovers** [comment]
Hi,

I did put the [pgn ...] into the "shortcode block" but I don't see any interactive diagrams being loaded. 

![short code 1](https://user-images.githubusercontent.com/91118138/134408109-2a2f8c0b-86f4-4763-acd0-d639ff0ff747.png)

As for the URL, I actually used a curator plugin that automatically uploads articles to my posted YouTube videos. There is no hyperlink to the articles. It is as good as writing a normal post.

I have included this particular page for your reference. 
https://chesslovers.reviewston.com/nona-gaprindashvili-sues-netflix-for-5-million-dollars/

Thank you.

**Comment by yo35** [comment]
If you press key F12 in your browser (must be Chrome or Firefox) and clicks on tab "Console", it shows the JavaScript errors that occur during the page load. On your example, there is this "$.chessgame is undefined" error:

![screenshot](https://user-images.githubusercontent.com/5740068/134413726-1a22a7ca-cf1d-4896-8e4e-c4d0aaf2af21.png)

This is because the widget showing the game tries to render too early while the browser loads the page. I don't understand why, this may be due to the theme, or to another plugin that hacks the way the JavaScript scripts are loaded and executed. You may try to fix that by disabling lazy-loading of CSS/JavaScript files in the options of RPB Chessboard: this is in the admin, menu "Chess" > "Settings" > "Compatibility settings" > untick "Lazy-loading for CSS/JavaScript files".

Even if this works, there would probably still be an issue with JavaScript loading in your set-up, and the "$(...).sticky" error would probably be still there (altough this one is not related to RPB Chessboard).

**Comment by ChessLovers** [comment]
Thank you so much! 

I have unticked "Lazy-loading for CSS/JavaScript files" and it works! 

Once again, I really appreciate your knowledge and kind assistance.

Thank you.
