### ISSUE TITLE
Space at beginning of comments

### ISSUE THREAD

**Issue by Ballintleave** [yo35/rpb-chessboard#220]
When writing comments a space appears after the {
Whilst this may be OK most of the time, it causes a formatting error if the first character after the { is a punctuation mark such as a comma ,
The result is something like: "16.Bd2 ,jettisoning the " 
instead of "16.Bd2, jettisoning the " 

Could this be remedied?

**Comment by yo35** [comment]
Hi,

This problem is not that simple to fix, because it would require to make the plugin guess when a space needs to be automatically added before the comment, and when it is not the case. I don't see any way to achieve this taken into account all the possible situations: for instance, what should we do after move `16.Bd2+` (`+` and `,` without space in between is weird, right) ? And after a move with a NAG, such as `16.Bd2 !` ? And what if the comment starts with `;` or `:` ? (space is required before those guys in some languages such as French, but not in English)

Also, between two behaviors that are not 100% OK but rarely fails, I prefer choosing the most simple one, because it is likely to be more easily understood by users.

**Comment by yo35** [comment]
Definitely, I will not change the behavior of the plugin on this issue, since it would require a significantly large amount of work, for minor (and possibly questionable) benefit.

**Comment by Ballintleave** [comment]
Understood.
