### ISSUE TITLE
What does this mean : Qf6 $9  ?

### ISSUE THREAD

**Issue by JustEggbird** [yo35/rpb-chessboard#255]
What does this mean : Qf6 $9  ?

**Comment by yo35** [comment]
https://rpb-chessboard.yo35.org/documentation/pgn-syntax/#chess-assessment-symbols

**Comment by JustEggbird** [comment]
$9 is not in the NAG table ........

**Comment by yo35** [comment]
Yes, and since the table "lists the symbols supported by RPB Chessboard", it is not supported.

https://en.wikipedia.org/wiki/Numeric_Annotation_Glyphs states that `$9` means "worst move", but there is no standard symbol associated to it. I don't know from which software you get a PGN file with `$9`.

**Comment by JustEggbird** [comment]
from chess.com .....

**Comment by yo35** [comment]
... and how is it rendered on chess.com ?

**Comment by JustEggbird** [comment]
![Knipsels2](https://user-images.githubusercontent.com/53820590/224545758-343fcbde-d138-46ed-b782-6ea90da71875.PNG)

**Comment by JustEggbird** [comment]
Maybe introducing a new symbol ? to be compatible ....
![Knipsels](https://user-images.githubusercontent.com/53820590/225462157-66bd4e82-fe26-4271-a832-e5f877191205.PNG)

**Comment by yo35** [comment]
`$9` is now supported in version 7.4.0 (just released).
