### ISSUE TITLE
Error showing game to not logged in users

### ISSUE THREAD

**Issue by naujoel** [yo35/rpb-chessboard#278]
Surprisingly, when a user is not logged in to my website, the plugin looks bad, but when logged in it looks perfect. You can view screenshots attached:

![Captura desde 2024-01-07 13-02-32](https://github.com/yo35/rpb-chessboard/assets/10756578/94978957-9fcb-4ab8-85ac-7975c51eaaf5)

![Captura desde 2024-01-07 13-03-12](https://github.com/yo35/rpb-chessboard/assets/10756578/06f413be-4e79-422c-82c1-fe3cbddba73f)

I've tried a lot of things but obviously I haven't tried everything yet.

I have tried changing the permissions of the files and directories to 777; I have purged the site and browser caches several times, until disabling them completely; I have checked that javascript is activated in the different browsers; I have tried several WordPress themes and the same thing happens in all of them; I have set the default Wordpress .htaccess; The site works fine with all the plugins installed, it only happens with this one...

So I don't know what I can do anymore.

Has this problem happened to anyone else? is there a solution for this problem? Thank you.

**Comment by yo35** [comment]
What is the address of your website ? (typically the address of a page/post with this game)

**Comment by naujoel** [comment]
Hello, thanks for answering. You can see the error in the following link: https://www.chesscampus.com/nepomniachtchi-vs-wang-hao-torneo-de-candidatos-2020/

**Comment by yo35** [comment]
Have you tried to disable lazy-loading of RPBChessboard-related CSS/JavaScript files? In settings > RPB Chessboard > Compatibility settings.

**Comment by yo35** [comment]
And by the way, there are some JavaScript errors on the page (see in the JavaScript console, available with F12 on Chrome or FF):

![js-error](https://github.com/yo35/rpb-chessboard/assets/5740068/06133f92-349c-48bd-983d-1ddc425a5c48)

This is not related to RPB Chessboard (it looks like the theme tries to fetch the user's avatar, which is of course not available since no user is logged), but it may impact it if the error is not caught properly. I suggest you report the problem to the theme author.

**Comment by naujoel** [comment]
Thanks for your quick response. We have managed to solve it. It was indeed a problem with the Wordpress theme:

https://www.chesscampus.com/nepomniachtchi-vs-wang-hao-torneo-de-candidatos-2020/

Thanks again. Greetings.
