### ISSUE TITLE
Scrolling the board while scrolling the page [feature request]

### ISSUE THREAD

**Issue by buffos** [yo35/rpb-chessboard#31]
Since i had to change the ".uichess-chessgame-floatLeft" position to relative i thought it would be nice and logical to scroll the board with while we scroll the document.

i guess this is pretty easy 
a) just s = getElementByClassName("uichess-chessgame-floatLeft")[0]
b) add an eventListener for on scroll
c) Get the top position of the s element (the board) in the document using 
v = s.getBoundingClientRect().top
d) the in the onscrollEvent callback just monitor drop = document.body.scrolltop - v + threshold >0
(threshold is a fixed value based on the design of the page if there any fixed toolbar on the top and the user will just that globally and by default has the value in pixels of the wordpress toolbar)

so if drop>0 then just s.style.top = drop and the board will drop

ofcourse one should check that drop < container.bottom which you can get from getBoundingClientRect.bottom from the correct div

**Comment by yo35** [comment]
Hi,

Sorry for being late to reply.

My question is: if you want to keep the board visible while the document gets scrolled, why don't you make the board appear in the popup window instead of in a "float-left" position?

**Comment by smigielski** [comment]
Hi,

I have quite the same problem. 

Let me first explain what is the use case here. I would like to have open chessboard always no matter how far I scroll down the game. If annotated game is longer, chessboard other than popup stops being visible. 

With just the popup the problem is that user has to know that to open the chessboard he has to click some move. This is not obvious.

I was thinking to use popup and than somehow trigger auto open with some calculated position that board is always on right side of the annotated game and is visible but it seems not to be trivial. 

Do you have some ideas how to solve this problem?

/Marek

**Comment by yo35** [comment]
Hi,
Making the popup appear when the navigation gets hidden is feasible, but it is not easy. I would say that the main problem is to determine where on the page the popup should be made visible without being too invasive.

**Comment by smigielski** [comment]
I am thinking of one more possibility to add chessboard on the right or left side and make a fixed height of the box with scrollable text. 

Something like here:
![screen shot 2016-10-07 at 14 10 05](https://cloud.githubusercontent.com/assets/542611/19189370/f625ab36-8c97-11e6-8c46-c13eeb0a0994.png)

Maybe this is a simple option.

**Comment by yo35** [comment]
Hi,
Thanks for the patch, I will try to test it this week. Looks OK.

**Comment by yo35** [comment]
Available in RPB Chessboard version 4.6, just released.
