### ISSUE TITLE
Moves keeps going past my screen

### ISSUE THREAD

**Issue by kenan628** [yo35/rpb-chessboard#45]
I am new to all of this and around move 8 on my site the moves go into abyss and never come back is there away to fix this?

**Comment by kenan628** [comment]
http://acechess.org/?page_id=435

**Comment by yo35** [comment]
Hi,
In your page, the shortcode `[pgn] ... [/pgn]` was surrounded by the HTML tag `<pre> ... </pre>`, whose default behavior is to disable automatic line breaks and carriage returns. I don't know why there are `<pre> ... </pre>` tags in your page: it may be because you have selected the "preformatted" style in the page editor, it may be because of your theme, etc...
