### ISSUE TITLE
TypeError: e.widget.extend is not a function

### ISSUE THREAD

**Issue by digitalStyx** [yo35/rpb-chessboard#49]
Hi 

When I turn on this plugin and add chessboard on sample page i've got error

``` javascript
TypeError: e.widget.extend is not a function
```

I read that can be related with a double loading jquery-ui http://stackoverflow.com/questions/13631325/jquery-ui-typeerror-e-widget-extend-is-not-a-function
but i don't know how

I'm use:
Cherry Lazy Load Boxes Plugin
Cherry Plugin
MotoPress Content Editor

My page with this error: http://akademia-szachowa-mat.pl/chessboard/

**Comment by yo35** [comment]
Hi,
I think the problem is due to file `http://akademia-szachowa-mat.pl/wp-content/themes/CherryFramework/js/jquery.mobile.customized.min.js`, which seems to include its own version of jQuery UI Widget (not sure of that, but it looks like). Could you delete it (temporarily) and then check whether or not you still get the error without it?

**Comment by digitalStyx** [comment]
yep, you're right, when I remove this file then it works

I think it has to do with incompatibility between jquery-mobile and jquery-ui described here
https://github.com/jquery/jquery-mobile/issues/4805

cherryframework for WP use very old library (jquery 1.7.2), I try to update them, also UI and mobile

**Comment by yo35** [comment]
RPB Chessboard uses the versions of jQuery and jQuery UI that are packaged by default with WP (respectively v1.11.3 and v1.11.4).

As a developer, I do not understand why Cherry Framework includes its own version of jQuery instead of using the one provided by WP. My opinion is that not using the default libraries is a bad practice in a "pluggable environment" such as WordPress. The fact that it uses a library that has not been upgraded for years makes this practice even worst as it can entail some security issues.

My advice is that you should request support from Cherry Framework. I would be surprised if RPB Chessboard were the only plugin affected by this "wild" JS inclusion.

**Comment by globalcultura** [comment]
Thank you for your work.

Same issue here http://colombiacultura.com/2015/12/05/ajedrez/ 

I can't find which plugin is incompatible and I can't disable all plugins to test it :-(

Any idea?

**Comment by yo35** [comment]
Hi,

Your problem comes from the following script:
`https://s.ytimg.com/yts/jsbin/www-embed-player-vfltVjsa9/www-embed-player.js`

Its execution fails (the error message is: `Error: Permission denied to access property "toString"`), which interrupts the execution of all further JavaScript code, including the RPB Chessboard Javascript code.

It's up to you to find which plugin of your website includes this bad script.

**Comment by globalcultura** [comment]
Thank you for the info,

**Comment by arunjchess** [comment]
I'm facing the same issue. When I check console, I get the following error: 

TypeError: a.widget.extend is not a function
a.Widget.prototype._createWidget()
 widget.min.js:11
a.widget/a[j][b]()
 widget.min.js:11
a.widget.bridge/a.fn[b]/<()
 widget.min.js:11
.each()
 jquery.js:2
m.prototype.each()
 jquery.js:2
a.widget.bridge/a.fn[b]()

What should I do ?

**Comment by yo35** [comment]
Hi,

You may try to remove the .js script file that causes the problem, as it is mentioned above in this thread.

**Comment by arunjchess** [comment]
My concern is: a. Will it stop some other function in the site from working? I'm not a very technical person. 
b. Where and what do I delete exactly? The site for which I'm asking you is mauriceashley (dot) com
I think it runs montreal wordpress theme.

**Comment by LAKnoKAL** [comment]
Hi,
Can you help me with my issue, please ?)

I have such an errors:
1. Uncaught TypeError: Cannot read property 'i18n' of undefined
2. Uncaught TypeError: $(...).removeClass(...).chessboard is not a function

http://www.dayandknight.co/blog/pgn-testing/  -  link on page where i have a problem

Thanks, 
Andrew

**Comment by yo35** [comment]
@LAKnoKAL I think your problem comes from the following JavaScript file:

`https://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js`

It seems that this script includes its own version of jQuery, regardless of the previously loaded components. I suggest you disable - at least temporarily - the plugin (MailChimp ?) that includes this file, to be sure of the cause of the problem.

**Comment by LAKnoKAL** [comment]
yo35, thanks for answer

I deactivated a MailChimp plugin, but errors are not corrected. Then i deactivated all my plugins, excerpt RPB Chessboard, but nothing has changed too.

Really looking forward to your reply,
Thanks

**Comment by yo35** [comment]
@LAKnoKAL I've investigated more thoroughly your problem. It seems that, at some point, your theme includes its own version of jQuery. See the following line in the HTML code of your page:

`<script type='text/javascript' src='http://www.dayandknight.co/blog/wp-content/themes/DayAndKnight/js/jquery-1.11.3.min.js?ver=4.4.2'></script>`

I don't understand why your theme needs to do that. But by replacing this line by the following one:

`<script type="text/javascript">$ = jQuery;</script>`

I get no error on the page, and everything seems to be OK.

**Comment by LAKnoKAL** [comment]
@yo35 Thnx a lot! The issue was with jquery versions, i just changed 1.11.3 version to 1.9.1.

**Comment by tutiitut** [comment]
Hi, I also have the same proplem - I have tried disabling the plugins but to no avail.

This is my link:

http://www.spqrnews.com/rpb-chessboard/

Thanks

**Comment by yo35** [comment]
As of RPB Chessboard version 7.0, jQuery widget is not used anymore to render the chessboards and chess games. Thus the problems described here should not happen anymore.
