### ISSUE TITLE
Key $11 (=) not interpreted

### ISSUE THREAD

**Issue by fjpa** [yo35/rpb-chessboard#51]
Looks like RPB PGN player does not interpret key $11 which is used to indicate that a position is even (=). The issue is documented in attached screen shot.
![rpb issue](https://cloud.githubusercontent.com/assets/15965986/11323596/db219b3e-9115-11e5-9e3f-fdb9387d072d.jpg)

**Comment by yo35** [comment]
Fixed in version 4.2.1.

However, it seems that there is a confusion between NAGs $10 and $11 among chess softwares:
- According to the PGN specification (http://www6.chessclub.com/help/PGN-spec), $10 means "drawish position", while $11 means "equal chances, quiet position". No "official" symbol is however defined in the specification document.
- Chessbase seems to export symbol = as $11.
- SCID seems to export symbol = as $10.
- The Wikipedia page on NAG (https://en.wikipedia.org/wiki/Numeric_Annotation_Glyphs) indicates that symbol = is mapped as $10.
- etc...

Concerning RPB Chessboard, as of version 4.2.1, both $10 and $11 are rendered as symbol =.
