### ISSUE TITLE
i dont see diagrams

### ISSUE THREAD

**Issue by alecsandruotetea** [yo35/rpb-chessboard#56]
I use the shortcode for setting up a chessboard but after publish I see the code [fen] ...[/fen] without seeing the diagram at all. 
You can see AT http://sahinscoala.ro/lessons/lectia-i-tabla-de-sah/ 
What should I do?

Thanks in advance,
alex

**Comment by yo35** [comment]
Hi,
Same problem as in #49: you are using the Cherry Framework...

**Comment by loulemaismais** [comment]
Is there a way to make it work with Cherry Framework?
In my case, i don't see nothing, not even the code [fen]...[/fen]

**Comment by yo35** [comment]
Hi,
What is the address of your website?
As far as I know, there is still a problem with the Cherry Framework, due to the fact that they embed their own version of jQuery UI. More details about this in #49.

**Comment by loulemaismais** [comment]
Hi!

Thank you for your reply.

I read #49, but jquery / java script is too advanced for me (i'm not a
coder, i just  know something about HTML basics...)

My website is www.loulemaismais.pt


I tried the plugin here -
http://www.loulemaismais.pt/2016-2017/iii-divisao-serie-f-20162017/

there should be a diagram with the initial position after the 3rd period,
but there is only the rest of the text.



Thank you for your attention.



*Loulé ++ *
Clube de Xadrez
das Torres do al-Gharb
*Loulé Xeque-Mate, Torres ao Ataque! *
www.fb.com/xadrezloule <http://www.facebook.com/xadrezloule>

http://www.loulemaismais.pt
*Não temas nenhuma batalha, **junta-te à nossa muralha!*


2017-01-13 9:15 GMT+00:00 Yoann Le Montagner <notifications@github.com>:

**Comment by yo35** [comment]
Hi,
Your problem is exactly the one described in #49 (to see this: enable the development tools in Chrome or Firefox with the F12 key. In the JavaScript console, you will see the "a.widget.extend is not a function" error).
Unfortunately, there is no definitive solution to this problem. You can try the workaround proposed in #49, i.e. removing one of the .js file brought by the Cherry Framework. You should also complain to the author of Cherry Framework, to make them use the .js libraries advised by WordPress.
