### ISSUE TITLE
Chessboard not loading small-screens.css

### ISSUE THREAD

**Issue by jaredwolff** [yo35/rpb-chessboard#57]
Hey all,

Trying to load a very simple chessboard on a post. Getting some interesting errors. 

> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (small-screens.css, line 0)
[Error] TypeError: undefined is not an object (evaluating '$.chessgame.i18n')
	(anonymous function)
	(anonymous function)
[Error] TypeError: $(selector).removeClass('rpbchessboard-chessboardAnchor').chessboard is not a function. (In '$(selector).removeClass('rpbchessboard-chessboardAnchor').chessboard', '$(selector).removeClass('rpbchessboard-chessboardAnchor').chessboard' is undefined)
	(anonymous function)
	j
	fireWith
	ready
	J

Looks like the first issue is that i'm missing small-screens.css. Potentially this is causing the later errors because the class resides in small-screens.css?

**Comment by yo35** [comment]
Hi,
I think your problem is not related to `small-screens.css`. It looks like the JavaScript files brought by the plugin are not loaded properly.

What is the address of your website?

**Comment by jaredwolff** [comment]
Yoann,

From what I can tell, there is no small-screens.css provided in the plugin repo. Is it dynamically generated? Let me get you a link..

**Comment by yo35** [comment]
Hi,
`small-screens.css` is indeed dynamically generated. However, this file is optional (it contains some CSS instructions for small screen devices such as self-phones), and it definitively cannot be the cause of the JavaScript errors you encounter.

There is a problem in the HTML code of the page http://www.dayandknight.co/blog/pgn-testing/: some content appears before tags `<!DOCTYPE>` and `<html>`. This problem might be caused by your theme.

I'm not sure, but I would bet that the JavaScript files that are included before tags `<!DOCTYPE>` and `<html>` are not properly executed. Among these files there are `uichess-chessboard.min.js` and `uichess-chessgame.min.js`, that are supposed to be called to generated the chessboard and the PGN viewer. This would also explain why the jQuery accordion widget is not working properly.

**Comment by jaredwolff** [comment]
Hmm @yo35. Still having issues. My colleagues have posted more info on the other bug post. We can discuss there.
