### ISSUE TITLE
[REQ] flip board in real time

### ISSUE THREAD

**Issue by maximuss22** [yo35/rpb-chessboard#70]
Can you add Flip Board in real time?

See for example this project PGN4WEB

http://pgn4web-test.casaschi.net/wordpress/

If you press square E7 the board flip.

G8 for HELP shortcut command

thank you 

Max

**Comment by yo35** [comment]
Hi,
The problem is that I try to keep balance between having interesting features in the plugin and keeping it as simple as possible. And in this particular case, I'm not convinced that this feature would be useful enough compared to the required additional complexity (add a button for the user to flip the board + add the configuration options to let the post author hide or show the flip button).

And by the way, if this feature gets implemented in RPB Chessboard, it would not be implemented the way it is in pgn4web: unless you are a well-informed user, you never have the idea to click an a square to run an hidden action!

**Comment by yo35** [comment]
Done in version 5.0 (just released)
